### PR TITLE
Fix event handling

### LINKED ISSUE #4: Program does not terminate during generation
In a POSIX OS, SDL will capture the termination signals at initialisation. The signal will generate an `SDL_QUIT` event instead of terminating the program directly.
(Reference https://wiki.libsdl.org/SDL_EventType#Remarks)

Hence during generation, the events are not handled as generation work is occupying CPU. This leads to termination signals not being handled promptly and program keeps running.

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Fixes #4

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -33,24 +52,50 @@ int geo_main(void) {
...
+  SDL_Thread *worker = NULL;
+  worker_data_t worker_data = {renderer, NULL};
+
   while (running) {
     bool alive = true;
-    GEO_NewGeo(time(NULL));
-
-    SDL_SetRenderDrawColor(renderer, 0x20, 0x20, 0x20, 0x04);
-    View *view = GEO_NewView(renderer);
+    if (!worker_working) {
```
Comment (fangyi-zhou) [inline src/main.c]: There is a race condition here...

**Comment by MislankaNova** [comment]
Thank you very much for your contribution. There are a handful of very minor problems that can be trivially solved and I'll take care of them.
